v1.2.1 with pip check
conda-forge/fortranformat-feedstock pull request #8
Opened 2022-07-31 06:05 UTC by alexmalins

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

This is the same version update as PR #7 created by the bot, but this PR also adds a `pip check` test as recommended by conda-forge. If this PR is merged, #7 can be closed. If #7 is merged first, I'll have to update the build number in this recipe.

Current testing status:
Fortranformat's creator kindly added a minimal test suite suitable for CI pipelines into v1.2.1. These tests aren't packaged in the PyPI sdist however, as the test files are much larger than the main code source files.

Incorporating the minimaltests into this recipe may be possible in future in fortranformat starts making GitHub releases. See this [recipe](https://github.com/conda-forge/fastapi-offline-feedstock/blob/7f493b76ca0019fa1600aa1003ebab469499f34d/recipe/meta.yaml) as an example of where something similar is done (i.e. mixed download of PyPI package source tarball and tests from corresponding GitHub repo), and the discussion on the conda-forge [gitter](https://gitter.im/conda-forge/conda-forge.github.io) on July 27, 2022.

2022-07-31 06:06 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2022-08-02 06:50 UTC, smithsp requested changes
@alexmalins This is great.  Please add yourself to the recipe-maintainers, so that you can merge in the future.

2022-08-02 13:55 UTC, alexmalins commented
All done, thanks @smithsp

2022-08-02 14:21 UTC, smithsp approved these changes

2022-08-02 14:21 UTC, merged